name: weixin  
on:  
  workflow_dispatch:  
  schedule:   
    - cron: '0 1 * * *' # 假设您想要在北京时间上午7点运行，这是UTC时间上午1点  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
  
      - name: Set up Python 3.9  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.9  
  
      # 通常不推荐设置时区，但如果您确实需要，可以考虑在代码中处理  
      # - name: Set timezone (Optional and not recommended)  
      #   run: |  
      #     sudo timedatectl set-timezone Asia/Shanghai  
  
      - name: Install pip packages  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  
  
      - name: Run weixin script  
        run: python main.py
